[package]
name = "codeRust"
version = "0.1.0"
edition = "2021"
libc = "0.2.66"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust_gpiozero = "0.2.0"
